use role sysadmin;
use database eswar;
USE SCHEMA DATA;
CREATE OR REPLACE TABLE DIL(EMP_ID INT,NAME VARCHAR,DEPT VARCHAR,SALAR INT);
USE WAREHOUSE COMPUTE_WH; 
INSERT INTO DIL VALUES(101,'DILEEP','DEVELOPER',20000),(102,'ESWAR','DB ENGINEER',15000);

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE MASKING POLICY DIL_SESITIVE_INFO AS (VAL STRING) RETURNS STRING ->
CASE
WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN VAL
ELSE '********' END;

ALTER TABLE DIL MODIFY COLUMN DEPT SET MASKING POLICY DIL_SESITIVE_INFO;
SELECT * FROM "ESWAR"."DATA"."DIL";